// ─── Preset Equations ────────────────────────────────────────────────────────

export const PRESETS = [
  {
    name: 'Gaussian Wave Packet',
    type: 'wave',
    equation: 'Ψ(x,t) = A·exp(−(x−vt)²/4a²)·exp(i(kx−ωt))',
    params: { A: 1.5, k: 12, omega: 6, a: 2.5, v: 1.0 },
    sliders: [
      { key: 'A',     label: 'Amplitude A',       min: 0.1, max: 4,  step: 0.05 },
      { key: 'k',     label: 'Wave number k',      min: 1,   max: 25, step: 0.5  },
      { key: 'omega', label: 'Frequency ω',        min: 0.1, max: 15, step: 0.1  },
      { key: 'a',     label: 'Packet width a',     min: 0.5, max: 6,  step: 0.1  },
      { key: 'v',     label: 'Group velocity v',   min: -3,  max: 3,  step: 0.05 },
    ],
    description: '1D free-particle wave packet — Schrödinger solution',
  },
  {
    name: 'Van der Pol Oscillator',
    type: 'system',
    equation: "x'' − μ(1−x²)x' + x = 0",
    equations: ['dx/dt = y', 'dy/dt = μ(1−x²)y − x'],
    params: { mu: 1.5 },
    sliders: [
      { key: 'mu', label: 'Nonlinearity μ', min: 0.1, max: 5, step: 0.1 },
    ],
    systemFn: (s, _t, p) => [s[1], p.mu * (1 - s[0] * s[0]) * s[1] - s[0]],
    xRange: [-4, 4],
    yRange: [-6, 6],
    description: 'Self-sustained oscillations with limit cycle',
  },
  {
    name: 'Simple Pendulum',
    type: 'system',
    equation: "θ'' + sin(θ) = 0",
    equations: ['dθ/dt = ω', 'dω/dt = −sin(θ) − δ·ω'],
    params: { damping: 0 },
    sliders: [
      { key: 'damping', label: 'Damping δ', min: 0, max: 1, step: 0.01 },
    ],
    systemFn: (s, _t, p) => [s[1], -Math.sin(s[0]) - p.damping * s[1]],
    xRange: [-7, 7],
    yRange: [-4, 4],
    description: 'Nonlinear pendulum phase portrait',
  },
  {
    name: 'Cubic Root Finding',
    type: 'algebraic',
    equation: 'x³ − 2x + 0.5 = 0',
    params: { x0: 2 },
    sliders: [
      { key: 'x0', label: 'Starting guess x₀', min: -3, max: 3, step: 0.1 },
    ],
    fn:  x => x * x * x - 2 * x + 0.5,
    dfn: x => 3 * x * x - 2,
    xRange: [-2.5, 2.5],
    yRange: [-4, 4],
    description: 'Newton-Raphson iteration visualization',
  },
  {
    name: 'Duffing Oscillator',
    type: 'system',
    equation: "x'' + δx' + αx + βx³ = γcos(ωt)",
    equations: ['dx/dt = y', 'dy/dt = −δy − αx − βx³ + γcos(ωt)'],
    params: { delta: 0.3, alpha: -1, beta: 1, gamma: 0.5, omega: 1.2 },
    sliders: [
      { key: 'delta', label: 'Damping δ',         min: 0,   max: 1,  step: 0.01 },
      { key: 'alpha', label: 'Linear α',           min: -2,  max: 2,  step: 0.1  },
      { key: 'beta',  label: 'Cubic β',            min: 0,   max: 3,  step: 0.1  },
      { key: 'gamma', label: 'Drive amplitude γ',  min: 0,   max: 2,  step: 0.05 },
      { key: 'omega', label: 'Drive frequency ω',  min: 0.1, max: 3,  step: 0.1  },
    ],
    systemFn: (s, t, p) => [
      s[1],
      -p.delta * s[1] - p.alpha * s[0] - p.beta * s[0] ** 3 + p.gamma * Math.cos(p.omega * t),
    ],
    xRange: [-3, 3],
    yRange: [-3, 3],
    description: 'Chaotic forced oscillator',
  },
  {
    name: 'Lorenz System (x-z)',
    type: 'system',
    equation: 'ẋ=σ(y−x)  ẏ=x(ρ−z)−y  ż=xy−βz',
    equations: ['dx/dt = σ(y−x)', 'dy/dt = x(ρ−z)−y', 'dz/dt = xy − βz'],
    params: { sigma: 10, rho: 28, beta: 2.667 },
    sliders: [
      { key: 'sigma', label: 'σ',  min: 1,  max: 20, step: 0.5 },
      { key: 'rho',   label: 'ρ',  min: 1,  max: 50, step: 0.5 },
      { key: 'beta',  label: 'β',  min: 0.5, max: 5,  step: 0.1 },
    ],
    systemFn: (s, _t, p) => [
      p.sigma * (s[1] - s[0]),
      s[0] * (p.rho - s[2]) - s[1],
      s[0] * s[1] - p.beta * s[2],
    ],
    dim: 3,
    projX: 0,
    projY: 2,
    xRange: [-25, 25],
    yRange: [0, 55],
    description: 'Strange attractor — deterministic chaos',
  },
];
